version: '3.0'

services:
        dante:
                build:
                        context: dante
                        dockerfile: Dockerfile
                hostname: dante
                container_name: dante.local
                volumes:
                        - dante:/etc
                ports:
                        - "1080:1080"
                network_mode: "host"
                logging:
                        driver: syslog
                        options:
                                tag: dante
                restart: unless-stopped
volumes:
        dante:
                external: true
